@extends('layout.app')
@section('content')
    <section class="container-fluid-banner">
        <div class="col-12">
            <h1 class="h1-about">END USER LICENSE AGREEMENT</h1>
            <hr class="devider">
        </div>
    </section>
    <section class="main-div">
        <div style="padding:0px 80px; font-family: 'Montserrat';" class="col-12">
            <!--<h1 class="heading1">PARK SHADOWS HOA COOKIE POLICY</h1>-->
            <img src=" {{ asset('frontend/images/circle.png') }}" class="circle">
            <p class="paragraph">
            This End User License Agreement, including the Website Terms and Conditions and Privacy Policy, which are incorporated herein by reference (collectively referred to as the “Agreement”) is a binding agreement between Express Services, Inc. d/b/a Express Employment Professionals, an Oklahoma corporation (“Express”), and the business (whether an individual or entity) identified during the registration process for the Website (“Licensee”) (each a “party,” collectively the “parties”).<br><br>
            
            EXPRESS PROVIDES THE WEBSITE SOLELY ON THE TERMS AND CONDITIONS SET FORTH IN THE AGREEMENT AND ON THE CONDITION THAT LICENSEE ACCEPTS AND COMPLIES WITH THE AGREEMENT. BY CLICKING “I AGREE” YOU (A) ACCEPT THE AGREEMENT AND AGREE THAT LICENSEE IS LEGALLY BOUND BY THE TERMS SET FORTH BELOW AND INCORPORATED HEREIN; (B) REPRESENT AND WARRANT THAT YOU ARE 18 YEARS OF AGE; (C) AGREE TO THESE TERMS ON BEHALF OF YOURSELF INDIVIDUALLY AS WELL AS LICENSEE; AND (D) YOU HAVE THE RIGHT, POWER AND AUTHORITY TO ENTER INTO THIS AGREEMENT ON BEHALF OF LICENSEE AND BIND LICENSEE TO ITS TERMS. IF LICENSEE OR YOU DO NOT SO AGREE OR REPRESENT AND WARRANT, EXPRESS WILL NOT AND DOES NOT LICENSE THE RIGHT TO USE THE WEBSITE TO LICENSEE.<br><br>
             <ul>
                 <li><strong><u>Definitions.</u></strong> In addition to those terms otherwise defined herein, for purposes of this Agreement, the following terms have the following meanings:<br><br>
                <strong> “Authentication Information” </strong> means the user name, password, or other piece of information provided by Express to allow access to secure parts of the Website not otherwise publically available. <br>
                <strong> “Authorized Users” </strong> means only those employees and/or agents of Licensee that are provided Authentication Information by Express. <br>
                <strong> “Confidential Information” </strong> means any and all content or information placed on the Website by Express which requires Authentication Information to access, together with any other information proprietary and/or confidential to Express and which may be made available to Licensee, including without limitation, unpatented inventions, ideas, processes, trade secrets, research data, product development, know-how, show-how, guidelines (operational or otherwise), charts, diagrams, manuals, methods, policies, procedures, programs, software, firmware, specifications, standards (both operational and visual), strategies, marketing strategies, customer information, customer lists, supplier information, supplier lists, and that which is normally considered confidential or is indicated by Express to be confidential or proprietary, and any and all embodiments thereof, whether tangible or intangible, regardless of how documented, and regardless of whether created jointly or solely by Express or whether in existence as of the effective date of this Agreement or created thereafter. <br>
                <strong> “Intellectual Property Rights” </strong> means any and all registered and unregistered rights granted, applied for or otherwise now or hereafter in existence under or related to any patent, copyright, trademark, trade secret, database protection or other intellectual property rights laws, and all similar or equivalent rights or forms of protection, in any part of the world. <br>
                <strong> “Person” </strong> means an individual, corporation, partnership, joint venture, limited liability company, governmental authority, unincorporated organization, trust, association or other entity. <br>
                <strong> “Postings” </strong>means all information, data or content that is posted, submitted, transmitted, or otherwise made available on the Website by Persons other than Express, including Licensee. <br>
                <strong> “Released Parties” </strong>collectively refers to Express and its affiliates together with their respective parent and subsidiary entities as well as each of their respective employees, agents, officers, directors, and licensors. <br>
                <strong> “Third Party” </strong>means any Person other than Licensee or Express. <br>
                <strong> “Website” </strong> means the Website located at the domain client.express.com together with any and all sub-domains and affiliated websites thereof. 
                
                </li>
                 <br>
                 <li><strong><u>License.</u></strong> Subject to Licensee’s compliance with the terms and conditions of this Agreement, Express hereby grants Licensee and Licensee’s Authorized Users a limited, non-exclusive, nonsublicenseable, nontransferable, revocable, royalty-free license to access the Website during the term of this Agreement solely for Licensee’s Authorized Users to access and use the Website for Licensee’s internal business use (the “License”). Licensee and its Authorized Users grant Express and all Persons involved in the operation of the Website the right to transmit, monitor, store, retrieve and use information by Licensee and its Authorized Users in connection with the operation of the Website and to ensure compliance the terms of this Agreement.</li>
                 <br>
                 <li><strong><u>Restrictions</u></strong> Licensee shall not, and shall require that its Authorized Users do not, whether directly or indirectly: (a) allow Third Parties to use or access to the Website; (b) use or access the Website or its content in any commercial or non-commercial application or service except as provided in this Agreement; (c) sell, rent, lease, lend, license, sublicense, distribute or otherwise transfer Website content to any third party; (d) decompile, disassemble or reverse engineer the Website or its content, in whole or in part; (e) write or develop or attempt to distribute any derivative of or information based upon the Website or Website content; (f) without Express’s prior written consent, provide, disclose, divulge or make available to, or permit use of the Website or its content by any third party; (g) remove, delete, alter or obscure any trademarks or any copyright, trademark, patent or other intellectual property or proprietary rights notices provided on Website content; (h) use the Website in violation of any law, regulation or rule; (i) remove, disable, circumvent or otherwise create or implement any workaround to any copy protection, rights management or security features in or protecting the Website; (j) use the Website in, or in association with, the design, construction, maintenance or operation of any hazardous environments or systems; (k) use the Website for purposes of competitive analysis, the development of a competing product or service or any other purpose that is to Express’s commercial disadvantage; or (l) violate the Agreement.</li>
                 <br>
                 <li><strong><u>Responsibility for Use of Website</u></strong> Licensee is responsible and liable for all uses of the Website through access to the Website provided by Licensee, directly or indirectly. Specifically, and without limiting the generality of the foregoing, Licensee is responsible and liable for all actions and failures to take required actions with respect to the Website by its Authorized Users or by any other Person to whom Licensee or an Authorized User may provide access to or use of the Website, whether or not such access or use is permitted by or in violation of this Agreement. Licensee agrees that Authentication Information is Confidential Information and personal to each of Licensee’s Authorized Users and agrees not to provide any Third Party with access to the Website or portions of it. Licensee agrees to notify Express immediately of any unauthorized access to or use of Authentication Information or any other breach of security. Licensee also agrees to ensure its Authorized Users exit from the Website at the end of each session of use of the Website to mitigate the risk of unauthorized use, and to take precautions to prevent theft or loss of Authentication Information. <strong><u>Licensee has an affirmative obligation to notify Express if any Person provided Authentication Information is separated from Licensee’s employment or otherwise ceases to be affiliated with Licensee so that Express may take appropriate measures to prevent access to the Website by such Person(s).</u></strong> </li>
                 <br>
                 <li><strong><u>Maintenance and Support</u></strong> Express has no obligation to provide any maintenance or support or any level of service with respect to the Website, nor does Express make any representation, express or implied, with regard to the quality or operability of the Website or Website content.</li>
                  <br>
                 <li><strong><u>Intellectual Property</u></strong> Express shall retain all entire right, title and interest in and to the Website and information contained thereon, excluding the Postings, and, except for the limited License granted herein, nothing herein shall not be construed as a license, assignment or other transfer of any such right, title and interest to Licensee or its Authorized Users and Express is and shall be the sole and exclusive owner of the Website and Website content and all improvements in, modifications to, and/or derivative works thereof and/or the Confidential Information, together with all Intellectual Property Rights therein, whether or not developed, conceived and/or actually reduced to practice by Express solely or jointly with Licensee or otherwise. To the extent Licensee or any of its Authorized Users acquire rights in or to any of the foregoing, Licensee and its Authorized Users hereby grant, assign and transfer to Express, without the requirement of additional consideration, all right, title and interest (whether past, present or future) in and to the same. By submitting Postings, Licensee and its Authorized Users grant Express, our subsidiaries, affiliates, successors, and assigns a perpetual, irrevocable, worldwide, royalty-free, fully-paid, non-exclusive, and sub-licensable license to use, copy, display, distribute, modify, adapt, publish, translate, publicly perform and publicly display the Postings (in whole or in part) and to incorporate the Postings into other works in any format or medium now or later known, and to sublicense such rights through multiple tiers of sublicenses.</li>
                  <br>
                 <li><strong><u>Confidentiality</u></strong> Licensee agrees to protect and safeguard the confidentiality of all Confidential Information with at least the same degree of care as it would protect Licensee’s own confidential information, but in no event with no less than a reasonable degree of care. Licensee agrees not to use Confidential Information in any manner to Express’s detriment, including without limitation, to reverse engineer, disassemble, decompile or design around the same and further agrees not to disclose, or distribute, or publish, or copy, or reproduce, or sell, or lend, or manipulate, or otherwise make use of Confidential Information, except for the purpose of doing business with Express or to exercise the limited License hereunder, and not to disclose any such Confidential Information to any Third Party. Title 18, § 1833(b) of the United States Code provides that “[a]n individual shall not be held criminally or civilly liable under any Federal or State trade secret law for the disclosure of a trade secret that: (A) is made (i) in confidence to a federal, state, or local government official, either directly or indirectly, or to an attorney; and (ii) solely for the purpose of reporting or investigating a suspected violation of law; or (B) is made in a complaint or other document filed in a lawsuit or other proceeding, if such filing is made under seal.” Accordingly, the parties have the right to disclose trade secrets as allowed by 18 U.S.C. § 1833(b) and nothing in this Agreement is intended to conflict with 18 U.S.C. § 1833(b).</li>
                  <br>
                  <li><strong><u>Term & Termination</u></strong> This Agreement shall commence on the date on which you accept it via registration for Authentication Information and/or access to the Website and shall continue until the earlier of (i ) Licensee’s notice to Express to terminate this Agreement and cease use of the Website, which notice may be provided by using the Contact Us page of the Website; (ii) the termination of Licensee’s agreement with Express regarding personnel services provided to Licensee by Express; or (iii) Express terminates the Agreement, with or without notice, which termination may be with or without cause. In addition to the foregoing, Express may temporarily or permanently disable access to the Website by specific Authorized Users of Licensee and/or the operability of certain Authentication Information provided to Licensee for any or no reason, including, without limitation, an Authorized User’s separation of employment from Licensee and/or an actual or threatened breach of security. Nothing herein shall allow Licensee or any Authorized User to retain any copies of information or content found from the Website or images thereof. Sections 6, 7, 9 and 10 shall survive termination of this Agreement.</li>
                  <br>
                  <li><strong><u>Equitable Relief</u></strong> Licensee agrees and acknowledges that any actual or threatened breach of this Agreement by Licensee or its Authorized Users will cause injury to Express for which money damages would be an inadequate remedy and that, in addition to remedies at law, Express is entitled to equitable relief as a remedy for any such breach without the necessity of posting bond.</li>
                  <br>
                  <li><strong><u>Miscellaneous</u></strong> <br><br>
                    <ol>
                        <li>This Agreement constitutes the entire understanding of the parties relating to the subject matter herein, and revokes and supersedes all prior agreements regarding the same. To the extent there is a conflict with the terms of this End User License Agreement, the Website Terms and Conditions and/or the Privacy Policy, the following order of precedence applies: the express terms of the Website Terms and Conditions and the Privacy Policy shall be deemed incorporated herein by reference and the express terms of this End User License Agreement shall govern in the event of any conflict with any such incorporated terms unless expressly stated otherwise; and the express terms of the Website Terms and Conditions shall govern any conflict with the express terms of the Privacy Policy.</li>
                        <br>
                        <li>This Agreement shall not be assignable or otherwise transferable by Licensee without the prior written consent of Express, and any assignment or transfer made in violation of this provision shall be void. Express may assign or transfer this Agreement without Licensee’s consent. This Agreement shall be construed without regard to any presumption or rule requiring construction or interpretation against the party drafting an instrument or causing any instrument to be drafted. The headings and captions of this Agreement shall not be used to interpret or construe this Agreement. This Agreement may not be modified or amended except by written agreement signed by the parties hereto. This Agreement is divisible and separable. If any provision of this Agreement is held to be or becomes invalid, illegal or unenforceable, such provision or provisions shall be reformed to be as nearly possible to the intent of the parties and the remainder of the Agreement shall not be affected and shall remain valid and enforceable to the greatest extent permitted by law. This Agreement shall be binding on and shall inure to the benefit of the parties hereto, and their heirs, administrators, successors and assigns.</li>
                        <br>
                        <li>This Agreement does not constitute and shall not be construed as constituting a partnership or joint venture between the parties or as making either party an employee, agent or representative of the other. This Agreement shall be deemed executed and delivered when the Website user clicks “I Agree” which shall have the same effect as physical delivery of a signed original.</li>
                    </ol>
                  </li>
             </ul>
            </p>
        </div>
        <!--<div class="col-6">-->
        <!--    <img src=" {{ asset('frontend/images/new/gallery (3).jpg') }}"-->
        <!--        style="width: 95%; border-radius: 1.25rem !important;">-->
        <!--        <span class="d-flex justify-content-center font-weight-bold">-->
        <!--            BUY HERE! LIVE HERE!-->
        <!--        </span>-->
        <!--</div>-->
    </section>
    {{-- <section class="main-div1" style="padding-bottom: 70px;">
        <div class="col-5">
            <img src=" {{ asset('frontend/images/dot.png') }}" class="dot">
            <img src=" {{ asset('frontend/images/image2.png') }}" style="width: 100%; z-index: 000000; position: relative;">
        </div>
        <div class="col-7">
            <h1 class="heading1">Explore Our Amenities</h1>
            <p class="paragraph">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse bibendum,
                neque at
                congue ornare, tellus tellus consequat elit, consectetur ultricies lectus mauris sit amet magna.
                Quisque
                porta sit amet risus sit amet tempor. Nunc metus enim, porttitor et nisl a, consectetur porta ex.
                Vestibulum tincidunt vestibulum nisi, id malesuada nisl bibendum non. Proin ut mauris dictum,
                pulvinar
                erat nec, tristique lorem. Proin libero mi, pulvinar vitae quam nec, eleifend congue ex. Vestibulum
                et
                dolor et orci volutpat placerat eu ac ex.</p>
        </div>
    </section> --}}
    <!--<section class="container-fluid-banner">-->
    <!--    <div class="col-12">-->
    <!--        <div class="cta">-->
    <!--            <h1 class="h1-about">Get In Touch With Us</h1>-->
    <!--            <hr class="devider">-->
    <!--            <a href="{{ route('contact') }}"><button class="btn-2">Contact Us</button></a>-->
    <!--        </div>-->
    <!--    </div>-->
    <!--</section>-->
@endsection
